name: FirstSpigot
version: 1.0
main: pe.chalk.firstspigot.FirstSpigot

commands:
  test:
    description: Send message to sender
  test2:
    description: Send message to all
  cls:
    description: Clear chatting